version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: server.Dockerfile
    image: push_server
  client:
    build: 
      context: .
      dockerfile: client.Dockerfile
    image: pull_client


